{% set name = "pytest-datafiles" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 05fc3eef2429fe26ae42283cccb1f3831b53b12d4bd8b4734bf42973d4af6e16

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling

  run:
    - python >={{ python_min }}
    - pytest >=6.2.0

test:
  requires:
    - pip
    - pytest >=6.2.0
    - tox
    - python {{ python_min }}
  commands:
    - tox

about:
  home: https://github.com/omarkohl/pytest-datafiles
  summary: Pytest plugin to create a 'tmp_path' containing predefined files/directories
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotduarte
