{% set name = "pytest-datafiles" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a70c4c66a36d1cdcfc095607f04eee66eaef3fa64cbb62d60c47ce169901d1d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}
    - pytest >=3.6

test:
  requires:
    - pip
    - pytest >=3.6
    - tox
    - python {{ python_min }}
  commands:
    - tox

about:
  home: https://github.com/omarkohl/pytest-datafiles
  summary: Pytest plugin to create a 'tmp_path' containing predefined files/directories
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotduarte
